require('dotenv').config();
const mongoose = require('mongoose');
const Disease = require('./models/Disease');

const precautionsMap = {
  'Migraine': ['Lie down in a dark, quiet room immediately','Apply a cold or warm compress to your forehead or neck','Stay hydrated — dehydration worsens migraines','Take OTC pain relief (paracetamol or ibuprofen) at the very first sign','Avoid screens, bright lights, and loud sounds','Identify and avoid personal triggers (stress, certain foods, lack of sleep)','Keep a migraine diary to track patterns'],
  'Epilepsy': ['Do NOT restrain the person during a seizure — clear the area of hard objects','Turn the person on their side to prevent choking','Do NOT put anything in their mouth','Time the seizure — call emergency if it lasts more than 5 minutes','Stay with the person until they are fully conscious','Never leave an epileptic person alone near water or heights','Take prescribed anti-epileptic medication without missing doses'],
  'Stroke': ['⚠️ EMERGENCY — Call ambulance immediately — every minute counts','Use FAST test: Face drooping, Arm weakness, Speech difficulty, Time to call','Do NOT give food, water, or medication to the person','Lay the person down with head slightly elevated','Do NOT leave the person alone','Note the exact time symptoms started — critical for treatment','Do not drive to hospital — call emergency services'],
  "Parkinson's Disease": ['Take prescribed medications at exact scheduled times — never skip','Remove trip hazards at home — rugs, loose wires, slippery floors','Use handrails on stairs and grab bars in bathroom','Exercise daily — walking, swimming, or tai chi helps maintain mobility','Speak slowly and clearly — use voice exercises','Eat high-fibre diet to prevent constipation','Avoid alcohol and caffeine which can worsen tremors'],
  'Vertigo': ['Sit or lie down immediately when dizziness strikes — do not stand up suddenly','Move your head slowly — avoid sudden head movements','Try the Epley maneuver (head repositioning) for BPPV vertigo','Avoid driving or operating machinery during episodes','Stay hydrated and avoid caffeine and alcohol','Sleep with head slightly elevated on two pillows','Avoid bright lights and screens during an episode'],
  'Eczema (Atopic Dermatitis)': ['Moisturise skin immediately after bathing — use fragrance-free cream','Use mild, fragrance-free soap and detergent','Avoid scratching — trim nails short and wear cotton gloves at night','Wear loose, soft cotton clothing — avoid wool and synthetic fabrics','Apply a cold compress to relieve itching temporarily','Avoid known triggers — dust, pet dander, sweat, certain foods','Use lukewarm water for bathing — hot water worsens eczema'],
  'Psoriasis': ['Moisturise skin multiple times daily — use thick creams or ointments','Take short, lukewarm baths and pat skin dry gently','Expose affected areas to mild sunlight for 10–15 minutes daily','Avoid skin injuries, cuts, and sunburn — they trigger flare-ups','Manage stress through yoga, meditation, or exercise','Avoid alcohol and smoking — both worsen psoriasis','Do not pick or scratch plaques — it causes bleeding and infection'],
  'Acne Vulgaris': ['Wash face twice daily with a gentle, non-comedogenic cleanser','Do NOT pop or squeeze pimples — causes scarring and infection','Use oil-free, non-comedogenic moisturiser and sunscreen','Change pillowcases every 2–3 days','Avoid touching your face with unwashed hands','Reduce dairy and high-glycaemic foods (sugar, white bread)','Use benzoyl peroxide or salicylic acid products for mild acne'],
  'Urticaria (Hives)': ['Take an antihistamine (cetirizine or loratadine) for immediate relief','Apply a cold compress to reduce swelling and itching','Identify and avoid the trigger — food, medication, insect bite, latex','Wear loose, cool clothing — heat worsens hives','Avoid hot showers and strenuous exercise during a flare','⚠️ Seek emergency care if lips/throat swell or breathing is difficult (anaphylaxis)','Keep an epinephrine auto-injector if previously prescribed'],
  'Fungal Skin Infection': ['Keep the affected area clean and dry — fungi thrive in moisture','Apply over-the-counter antifungal cream (clotrimazole) twice daily','Wear loose, breathable cotton clothing and change daily','Do not share towels, clothing, or footwear with others','Wash clothes and bedding in hot water','Dry between toes thoroughly after bathing','Avoid walking barefoot in public showers or pools'],
  'Osteoarthritis': ['Apply ice pack for 15–20 minutes to reduce swelling after activity','Apply warm compress in the morning to ease stiffness','Do gentle low-impact exercise — swimming, cycling, walking','Maintain healthy weight — every kg lost reduces knee pressure by 4kg','Use a walking stick or knee support if needed','Avoid prolonged sitting or standing in one position','Take paracetamol for pain — avoid NSAIDs long-term without doctor advice'],
  'Fracture': ['⚠️ Do NOT try to straighten or move the injured limb','Immobilise the area with a splint or firm padding','Apply ice wrapped in cloth to reduce swelling — not directly on skin','Elevate the injured limb above heart level if possible','Do not apply pressure or massage the area','Seek emergency care immediately — do not delay','If bone is visible through skin, cover with clean cloth and go to ER'],
  'Herniated Disc': ['Rest for 1–2 days but avoid complete bed rest — gentle movement helps','Apply ice for first 48 hours, then switch to heat','Avoid bending forward, lifting heavy objects, or twisting the spine','Sleep on your side with a pillow between knees','Take paracetamol or ibuprofen for pain relief','Do gentle stretches — knee-to-chest stretch helps relieve pressure','Seek emergency care if you lose bladder/bowel control'],
  'Rheumatoid Arthritis': ['Apply warm compress in the morning to ease stiffness','Do gentle range-of-motion exercises daily','Rest during flare-ups — do not push through severe pain','Use assistive devices — jar openers, ergonomic tools to protect joints','Maintain a healthy weight to reduce joint stress','Eat anti-inflammatory foods — fish, nuts, leafy greens, turmeric','Do NOT stop prescribed DMARDs or biologics without doctor advice'],
  'Tendinitis': ['Rest the affected area — stop the activity that caused it','Apply ice for 15–20 minutes every 2–3 hours for first 48 hours','Use a compression bandage to reduce swelling','Elevate the affected limb when resting','Take ibuprofen or paracetamol for pain and inflammation','Do gentle stretching once acute pain subsides','Gradually return to activity — do not rush back to full intensity'],
  'Otitis Media (Ear Infection)': ['Apply a warm cloth or heating pad on low setting against the ear','Take paracetamol or ibuprofen for pain relief','Do NOT insert anything into the ear — no cotton buds','Keep the ear dry — avoid swimming and use earplugs when bathing','Sleep with the affected ear facing up to allow drainage','Avoid blowing nose too hard — it pushes bacteria into the ear','Seek care if fever is high, discharge is bloody, or pain is severe'],
  'Sinusitis': ['Inhale steam for 10 minutes twice daily — add eucalyptus oil for relief','Use saline nasal spray or rinse (Neti pot) to flush sinuses','Stay well hydrated to thin mucus','Apply warm compress over face to relieve pressure','Sleep with head elevated to improve drainage','Avoid cold air, smoke, and allergens','Use a humidifier in your room to keep air moist'],
  'Tonsillitis': ['Gargle with warm salt water every 2–3 hours','Drink warm liquids — honey-ginger tea, warm water with lemon','Eat soft, cool foods — ice cream, yogurt, smoothies ease throat pain','Take paracetamol for fever and pain','Rest your voice — avoid talking loudly or whispering','Use a humidifier to keep air moist','Avoid cold drinks, spicy food, and smoking'],
  'Allergic Rhinitis': ['Take an antihistamine (cetirizine or loratadine) for immediate relief','Use saline nasal spray to flush allergens from nasal passages','Keep windows closed during high pollen season','Use air purifier with HEPA filter at home','Wash bedding weekly in hot water to kill dust mites','Shower after coming indoors to remove pollen from hair and skin','Wear sunglasses outdoors to protect eyes from pollen'],
  'Childhood Fever & Infection': ['Give paracetamol syrup (correct dose for weight) to reduce fever','Keep the child hydrated — ORS, water, diluted juice, breast milk','Dress child in light clothing — do not over-bundle','Sponge with lukewarm water if fever is very high','Monitor temperature every 4 hours','Do NOT give aspirin to children — risk of Reye\'s syndrome','Seek emergency care if fever exceeds 104°F, child has seizure, or is unresponsive'],
  'Asthma in Children': ['Use the prescribed reliever inhaler (blue) immediately during an attack','Sit the child upright — do not lay them down during breathing difficulty','Keep the child calm — anxiety worsens breathing','Remove the child from the trigger environment (smoke, dust, cold air)','Use a spacer with the inhaler for better delivery','Keep the home dust-free — vacuum regularly, use allergen-proof covers','⚠️ Call emergency if inhaler gives no relief after 10 minutes'],
  'Chickenpox': ['Keep the child at home — chickenpox is highly contagious until all blisters crust','Apply calamine lotion to blisters to relieve itching','Trim child\'s nails short to prevent scratching and scarring','Give paracetamol for fever — strictly avoid aspirin','Dress child in loose, soft cotton clothing','Give lukewarm oatmeal baths to soothe skin','Do NOT let child scratch — use mittens at night if needed'],
  'Diarrhea & Dehydration in Children': ['Give ORS (oral rehydration solution) in small sips every few minutes','Continue breastfeeding if the child is an infant','Offer bland foods — rice water, banana, boiled potato, toast','Avoid fruit juices, sugary drinks, and dairy during diarrhea','Do NOT give anti-diarrheal medication to children without doctor advice','Watch for dehydration signs — sunken eyes, dry mouth, no tears, no urination','Seek emergency care if child is lethargic, has blood in stool, or cannot keep fluids down'],
  'Pregnancy Care': ['Start folic acid (400mcg) immediately — reduces neural tube defects','Avoid alcohol, smoking, and raw/undercooked food completely','Take prenatal vitamins as prescribed — iron and calcium are essential','Stay hydrated and eat small, frequent nutritious meals','Avoid heavy lifting, contact sports, and extreme physical exertion','Attend all scheduled antenatal checkups and ultrasounds','Seek immediate care if you have bleeding, severe pain, or reduced fetal movement'],
  'PCOD / PCOS': ['Maintain a healthy weight — even 5–10% weight loss improves symptoms significantly','Follow a low-glycaemic diet — avoid sugar, white rice, maida, processed foods','Exercise for at least 30 minutes daily — helps regulate insulin and hormones','Manage stress through yoga, meditation, or adequate sleep','Track your menstrual cycle to identify patterns','Avoid smoking — it worsens hormonal imbalance','Do not self-medicate with hormonal pills — consult a doctor'],
  'Endometriosis': ['Apply a heating pad or hot water bottle to the lower abdomen for cramp relief','Take ibuprofen at the first sign of period pain — before it becomes severe','Gentle exercise like yoga and walking can reduce pain over time','Avoid caffeine and alcohol during your period — they worsen cramps','Track symptoms in a diary to share with your doctor','Eat anti-inflammatory foods — omega-3 rich fish, leafy greens, turmeric','Do not ignore severe pain — early diagnosis prevents complications'],
  'Urinary Tract Infection (UTI)': ['Drink at least 2–3 litres of water daily to flush bacteria','Urinate frequently — do not hold urine for long periods','Wipe front to back after using the toilet','Urinate after sexual intercourse to flush bacteria','Avoid scented soaps, sprays, and bubble baths in the genital area','Wear loose, breathable cotton underwear','Cranberry juice may help prevent recurrence — but is not a treatment'],
  'Menopause': ['Dress in layers — remove clothing during hot flashes','Keep bedroom cool and use light bedding for better sleep','Stay hydrated and avoid caffeine, alcohol, and spicy food (hot flash triggers)','Exercise regularly — helps with weight, mood, and bone density','Eat calcium-rich foods — dairy, leafy greens, sesame seeds for bone health','Practice stress management — yoga, meditation, or counselling','Do not self-medicate with hormonal supplements — consult a doctor'],
  'Gastritis / Stomach Inflammation': ['Avoid spicy, oily, and acidic foods (citrus, tomatoes, vinegar)','Eat small, frequent meals instead of large ones','Avoid alcohol, caffeine, and carbonated drinks','Do not lie down immediately after eating — wait at least 2 hours','Take an antacid (e.g. Gelusil, Digene) for temporary relief','Drink plenty of water and stay hydrated','Avoid NSAIDs like ibuprofen — use paracetamol if needed for pain'],
  'Irritable Bowel Syndrome (IBS)': ['Identify and avoid trigger foods (dairy, gluten, beans, cabbage)','Eat at regular times and avoid skipping meals','Manage stress through deep breathing or light exercise','Increase dietary fibre gradually (fruits, vegetables, oats)','Stay well hydrated — drink 8–10 glasses of water daily','Avoid eating too fast — chew food thoroughly','Keep a food diary to track what worsens symptoms'],
  'Food Poisoning': ['Stay hydrated — sip ORS (oral rehydration solution) or coconut water frequently','Rest and avoid solid food for a few hours until nausea settles','Start with bland foods — rice, toast, bananas, boiled potatoes','Avoid dairy, fatty, spicy, or sugary foods until recovered','Do NOT take anti-diarrheal medication without doctor advice','Wash hands thoroughly before eating or touching face','Seek immediate help if vomiting is severe or blood appears in stool'],
  'Viral Fever': ['Rest completely and avoid physical exertion','Stay hydrated — drink water, coconut water, or ORS every hour','Take paracetamol (not ibuprofen) to reduce fever','Use a damp cloth on forehead to bring down temperature','Eat light, easily digestible food — khichdi, soup, fruits','Avoid cold drinks and ice cream','Wear light clothing and keep the room well-ventilated'],
  'Typhoid': ['Drink only boiled or bottled water — avoid tap water','Eat only freshly cooked, hot food — avoid raw vegetables and street food','Maintain strict hand hygiene — wash hands before eating and after toilet','Rest completely and avoid strenuous activity','Take paracetamol for fever — avoid aspirin','Eat soft, easily digestible foods — rice, dal, boiled vegetables','Isolate yourself to prevent spreading to family members'],
  'Dengue Fever': ['Drink plenty of fluids — water, ORS, papaya leaf juice, coconut water','Take paracetamol ONLY for fever — strictly avoid aspirin and ibuprofen','Rest completely — do not exert yourself','Use mosquito repellent and sleep under a mosquito net','Wear full-sleeve clothing to prevent further mosquito bites','Monitor platelet count — get blood test every 24–48 hours','Seek emergency care immediately if bleeding occurs or fever spikes above 104°F'],
  'Malaria': ['Use mosquito nets and repellents — eliminate stagnant water around home','Stay hydrated with ORS, water, and light fluids','Take paracetamol for fever and chills — avoid self-medicating with antimalarials','Rest completely and avoid cold exposure during chills','Eat light, nutritious food — avoid heavy or oily meals','Wear full-sleeve clothes especially at dawn and dusk','Get a blood smear test confirmed before starting any treatment'],
  'Diabetes': ['Avoid sugary foods, white rice, maida, and sweetened drinks','Eat small, balanced meals at regular intervals — do not skip meals','Walk for at least 30 minutes daily','Monitor blood sugar levels regularly if you have a glucometer','Stay well hydrated — drink water, not juices or sodas','Inspect feet daily for cuts or sores — wear comfortable footwear','Do not stop prescribed medication without doctor advice'],
  'COVID-19': ['Isolate yourself immediately — stay in a separate room','Wear a mask and maintain distance from family members','Monitor oxygen levels with a pulse oximeter — seek help if below 94%','Stay hydrated and rest completely','Take paracetamol for fever — avoid self-medicating with antibiotics','Ventilate your room — open windows for fresh air','Seek emergency care if breathing becomes difficult or chest pain occurs'],
  'Hypertension': ['Reduce salt intake — avoid pickles, papad, processed foods','Avoid caffeine, alcohol, and smoking','Practice deep breathing or meditation for 10 minutes daily','Avoid sudden physical exertion or lifting heavy weights','Sit or lie down if you feel dizzy — do not stand up suddenly','Monitor BP at home if you have a BP machine','Do NOT stop prescribed BP medication without doctor advice'],
  'Coronary Artery Disease': ['⚠️ If chest pain is severe or radiates to arm/jaw — call emergency immediately','Sit or lie down and rest — avoid any physical activity','Chew an aspirin (325mg) if available and not allergic — only if suspected heart attack','Loosen tight clothing around chest and neck','Avoid smoking, alcohol, and fatty foods','Do not drive yourself to hospital — call someone or an ambulance','Keep nitroglycerin spray/tablet handy if previously prescribed'],
  'Heart Failure': ['Restrict fluid intake as advised — typically 1.5–2 litres per day','Reduce salt intake strictly — avoid all processed and packaged foods','Weigh yourself daily — report sudden weight gain of 2kg+ to doctor','Sleep with head elevated (2–3 pillows) to ease breathing','Avoid strenuous activity — rest frequently','Do not stop diuretics or heart medications without doctor advice','Seek emergency care if breathlessness worsens suddenly'],
  'Arrhythmia': ['Sit or lie down immediately when palpitations occur','Try the Valsalva maneuver — bear down as if having a bowel movement for 10–15 seconds','Avoid caffeine, energy drinks, alcohol, and smoking','Reduce stress — practice slow deep breathing','Avoid cold medicines containing decongestants (pseudoephedrine)','Do not drive or operate machinery during an episode','Seek emergency care if you faint, have chest pain, or episode lasts over 30 minutes'],
};

async function addPrecautions() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected');

  let updated = 0;
  for (const [name, precautions] of Object.entries(precautionsMap)) {
    const result = await Disease.updateOne({ disease_name: name }, { $set: { precautions } });
    if (result.modifiedCount > 0) { updated++; console.log(`✅ ${name}`); }
    else console.log(`⚠️  Not found: ${name}`);
  }

  console.log(`\nDone — updated ${updated} diseases`);
  process.exit(0);
}

addPrecautions().catch(e => { console.error(e); process.exit(1); });
